export default {
  products: [
    {
      _id: '1',
      name: 'D&D-14 ANALOG DISPLAY WATCH ',
      category: 'Shirts',
      image: '../images/product-1.jpg',
      price: 59,
      brand: 'PIRASO',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'LCS-4116 Analog Watch ',
      category: 'Shirts',
      image: '../images/product-2.jpg',
      price: 70,
      brand: 'LOIS CARON',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: '2038-WH Analog Watch ',
      category: 'Shirts',
      image: '../images/product-3.jpg',
      price: 59,
      brand: 'Fogg  ',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'LCS-8189 Analog Watch ',
      category: 'Pants',
      image: '../images/product-4.jpg',
      price: 90,
      brand: 'LOIS CARON ',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: '77106SM04 Analog Watch',
      category: 'Pants',
      image: '../images/product-5.jpg',
      price: 119,
      brand: 'SONATA',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: '800 Sports Digital Watch',
      category: 'Pants',
      image: '../images/product-6.jpg',
      price: 85,
      brand: 'EDDY HAGER ',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ]
};